version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis-server
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    command: redis-server --save 60 1 --loglevel warning

  flask-app:
    build: .
    container_name: flask-iss
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - redis

